#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xB26995E310250568 (lukasz@python.org)
#
Name     : retype
Version  : 19.9.0
Release  : 20
URL      : https://files.pythonhosted.org/packages/2e/d1/37b8d4f29f1684a36a660b905401d3fedabdfa6af89a885d34bce31cf149/retype-19.9.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/2e/d1/37b8d4f29f1684a36a660b905401d3fedabdfa6af89a885d34bce31cf149/retype-19.9.0.tar.gz
Source1 : https://files.pythonhosted.org/packages/2e/d1/37b8d4f29f1684a36a660b905401d3fedabdfa6af89a885d34bce31cf149/retype-19.9.0.tar.gz.asc
Summary  : re-apply types from .pyi stub files to your codebase
Group    : Development/Tools
License  : MIT
Requires: retype-bin = %{version}-%{release}
Requires: retype-license = %{version}-%{release}
Requires: retype-python = %{version}-%{release}
Requires: retype-python3 = %{version}-%{release}
Requires: click
Requires: pathspec
Requires: typed_ast
BuildRequires : buildreq-distutils3
BuildRequires : click
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : typed_ast
BuildRequires : virtualenv

%description
# retype
[![Build Status](https://dev.azure.com/ambv/retype/_apis/build/status/ambv.retype?branchName=master)](https://dev.azure.com/ambv/retype/_build/latest?definitionId=1&branchName=master)

%package bin
Summary: bin components for the retype package.
Group: Binaries
Requires: retype-license = %{version}-%{release}

%description bin
bin components for the retype package.


%package license
Summary: license components for the retype package.
Group: Default

%description license
license components for the retype package.


%package python
Summary: python components for the retype package.
Group: Default
Requires: retype-python3 = %{version}-%{release}

%description python
python components for the retype package.


%package python3
Summary: python3 components for the retype package.
Group: Default
Requires: python3-core

%description python3
python3 components for the retype package.


%prep
%setup -q -n retype-19.9.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568387005
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/retype
cp LICENSE %{buildroot}/usr/share/package-licenses/retype/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/retype

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/retype/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
